# Generated by Django 4.2.7 on 2023-12-02 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoCurrencies', '0002_rename_cryptotokencurrencies_cryptotokencurrency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoTokenRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CryptoCurrencies.cryptotokencurrency')),
            ],
        ),
    ]
