# Generated by Django 4.2.7 on 2023-12-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoCurrencies', '0004_cryptotokenrate_rate_to_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptotokenrate',
            name='rate_to_usd',
            field=models.CharField(max_length=10),
        ),
    ]
