# Generated by Django 5.1 on 2024-08-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoCurrencies', '0013_alter_cryptotokenrate_rate_to_usd'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
