# Generated by Django 4.2.7 on 2023-11-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurrencyPairs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencypair',
            name='code',
            field=models.CharField(max_length=9),
        ),
    ]
