# Generated by Django 4.2.7 on 2023-11-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvailableCurrencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablecurrency',
            name='country_code',
            field=models.CharField(default='N/A', max_length=5),
        ),
        migrations.AddField(
            model_name='availablecurrency',
            name='country_name',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='availablecurrency',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='availablecurrency',
            name='code',
            field=models.CharField(max_length=5),
        ),
    ]
