# Generated by Django 4.2.7 on 2023-11-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvailableCurrencies', '0003_alter_availablecurrency_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablecurrency',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
