# Generated by Django 4.2.7 on 2023-11-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvailableCurrencies', '0004_alter_availablecurrency_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablecurrency',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
