# Generated by Django 4.2.7 on 2023-11-10 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AvailableCurrencies', '0007_alter_availablecurrency_country_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_to_usd', models.CharField(max_length=255)),
                ('date_updated', models.CharField(max_length=255)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AvailableCurrencies.availablecurrency')),
            ],
        ),
    ]
