# Generated by Django 4.2.7 on 2023-11-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvailableCurrencies', '0008_currencyexchangerate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyexchangerate',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='currencyexchangerate',
            name='api_date_updated',
            field=models.DateField(default='2023-11-10'),
            preserve_default=False,
        ),
    ]
