# Generated by Django 4.2.7 on 2023-11-12 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AvailableCurrencies', '0010_availablecurrency_user_currencyexchangerate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablecurrency',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AvailableCurrency', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CurrencyExchangeRate', to=settings.AUTH_USER_MODEL),
        ),
    ]
