# Generated by Django 4.2.7 on 2023-11-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvailableCurrencies', '0011_alter_availablecurrency_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablecurrency',
            name='example_file',
            field=models.FileField(blank=True, null=True, upload_to='AvailableCurrencies/examples/'),
        ),
    ]
