# Generated by Django 4.2.7 on 2023-11-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvailableCurrencies', '0012_availablecurrency_example_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablecurrency',
            name='image',
            field=models.ImageField(default=1, upload_to='app/images'),
            preserve_default=False,
        ),
    ]
