# Generated by Django 4.2.7 on 2024-02-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvailableCurrencies', '0013_availablecurrency_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablecurrency',
            name='code',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='availablecurrency',
            name='country_code',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
