# Generated by Django 5.1 on 2024-08-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvailableCurrencies', '0014_alter_availablecurrency_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=10)),
                ('currency_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
